-- Initial schema.
--
-- Identifiers are ULIDs generated by the door device, not by this backend. That is what
-- makes writes idempotent: the device retries from its local queue after a failed upload
-- and reuses the original id, so a backend outage must not arrive later as duplicate
-- rings in the house.
--
-- Timestamps are ISO 8601 UTC strings, stamped here. A cold-booting device has no
-- reliable wall clock, so it reports `device_uptime_ms` instead and the backend supplies
-- the time (ADR-002).

CREATE TABLE devices (
    device_id        TEXT PRIMARY KEY,
    name             TEXT,
    -- sleeping | awake | live | unreachable. Derived from event arrival and the
    -- staleness timeout, never from a connection: the device holds none.
    state            TEXT NOT NULL DEFAULT 'unreachable',
    last_seen        TEXT,
    last_event_id    TEXT,
    last_ring_at     TEXT,
    last_motion_at   TEXT,
    battery_voltage  REAL,
    rssi             INTEGER,
    wake_window_ends_at TEXT,
    created_at       TEXT NOT NULL,
    CHECK (state IN ('sleeping', 'awake', 'live', 'unreachable'))
);

CREATE TABLE events (
    id               TEXT PRIMARY KEY,
    device_id        TEXT NOT NULL REFERENCES devices(device_id) ON DELETE CASCADE,
    type             TEXT NOT NULL,
    occurred_at      TEXT NOT NULL,
    device_uptime_ms INTEGER,
    wake_reason      TEXT,
    battery_voltage  REAL,
    rssi             INTEGER,
    snapshot_id      TEXT,
    -- False when the server-side cooldown suppressed republishing. Stored rather than
    -- recomputed, so the event history says what actually happened.
    published_to_mqtt INTEGER NOT NULL DEFAULT 0,
    CHECK (type IN ('ring', 'motion')),
    CHECK (wake_reason IS NULL OR wake_reason IN ('button', 'motion', 'unknown')),
    CHECK (published_to_mqtt IN (0, 1))
);

-- History is read newest-first with a cursor on the timestamp, which is exactly this
-- index. Without it every history page is a full scan that grows with the event log.
CREATE INDEX idx_events_device_time ON events(device_id, occurred_at DESC);
CREATE INDEX idx_events_time ON events(occurred_at DESC);
CREATE INDEX idx_events_type_time ON events(type, occurred_at DESC);

CREATE TABLE snapshots (
    id               TEXT PRIMARY KEY,
    device_id        TEXT NOT NULL REFERENCES devices(device_id) ON DELETE CASCADE,
    -- Deliberately NOT a foreign key to events: the snapshot may be uploaded before the
    -- event row exists, since the device posts them as two requests and may retry either
    -- independently. Enforcing order here would reject a valid upload.
    event_id         TEXT,
    captured_at      TEXT NOT NULL,
    byte_size        INTEGER NOT NULL,
    width            INTEGER,
    height           INTEGER,
    -- Path relative to SNAPSHOT_DIR. Relative, so moving the volume does not invalidate
    -- every row.
    file_path        TEXT NOT NULL
);

CREATE INDEX idx_snapshots_device_time ON snapshots(device_id, captured_at DESC);
CREATE INDEX idx_snapshots_time ON snapshots(captured_at DESC);
CREATE INDEX idx_snapshots_event ON snapshots(event_id);

CREATE TABLE telemetry (
    id                  INTEGER PRIMARY KEY AUTOINCREMENT,
    device_id           TEXT NOT NULL REFERENCES devices(device_id) ON DELETE CASCADE,
    received_at         TEXT NOT NULL,
    device_uptime_ms    INTEGER,
    wake_reason         TEXT,
    boot_count          INTEGER,
    battery_voltage     REAL,
    rssi                INTEGER,
    free_heap_bytes     INTEGER,
    -- The least certain input in the power budget, and it costs nothing but a timestamp
    -- to report. Collecting it over time turns an assumption into data.
    wake_to_network_ms  INTEGER,
    upload_ms           INTEGER,
    queued_events       INTEGER
);

CREATE INDEX idx_telemetry_device_time ON telemetry(device_id, received_at DESC);
